### ISSUE TITLE
When will the codes be released?

### ISSUE THREAD

**Issue by PhoenixZ810** [ayushjain1144/odin#1]
Thanks for your great contribution! When will the codes be released? This can be very helpful.

**Comment by ayushjain1144** [comment]
Hi, 

Thank you for your interest. 

Tentatively in February is the plan currently.

Best,
Ayush

**Comment by PhoenixZ810** [comment]
It may be too late T^T

**Comment by ZCMax** [comment]
Hello, is there any progress about the code releasing?

**Comment by chenhaomingbob** [comment]
+1

**Comment by ayushjain1144** [comment]
we are working on it, should be out soon!
