### ISSUE TITLE
Run on multi GPU

### ISSUE THREAD

**Issue by eronez** [ayushjain1144/odin#12]
If run on multi GPUs whose number is more than 2,such as 3,4,5,
Which hyper parameter should be change?

**Comment by ayushjain1144** [comment]
I believe the default hyperparameters should work

**Comment by eronez** [comment]
> I believe the default hyperparameters should work

1
```shell
CUDA_VISIBLE_DEVICES=0,1 python train_odin.py  --dist-url='tcp://127.0.0.1:12345' --num-gpus 2
```
works well
screenshot
![image](https://github.com/ayushjain1144/odin/assets/55025357/b4b84b3b-c42f-4ed8-bbd3-bf351049758b)


2
```shell
CUDA_VISIBLE_DEVICES=0,1,2,3 python train_odin.py  --dist-url='tcp://127.0.0.1:12345' --num-gpus 4
```
took long time and no next output like above screenshot
screenshot
![image](https://github.com/ayushjain1144/odin/assets/55025357/85dce200-a4ec-4e78-b077-b63245fa1957)

Is it normal?

**Comment by ayushjain1144** [comment]
No, it isn't normal. 

Also, btw you need to update SOLVER.TEST_IMS_PER_BATCH=$num_gpus (4 in the second case)

**Comment by eronez** [comment]
Thank you. I finally found it's devices' fault.
