### ISSUE TITLE
Confuse About Unprojection in paper

### ISSUE THREAD

**Issue by AaronXenos** [ayushjain1144/odin#13]
![image](https://github.com/ayushjain1144/odin/assets/121851404/08b6e415-571c-4ee2-b4fc-0b37e6cbbda1)

In Appendix B,Figure 4. Detailed ODIN Architecture Components, "On the Left is the 3D RelPos Attention module which takes as input the depth, camera parameters and feature maps from all views, lifts the features to 3D to get 3D tokens."

1.Could you please show the location of code corresponding to "lifts the features to 3D"? Especially the part of "Depth Maps" and "Feature Maps".

2.Is it the func "get_multiview_xyz" in dataset_mapper_scannet.py?
But "Feature Maps" is not used in it.Maybe I misundertand the meaning.

3. part of resnet.py also use "project",but it project res to trans.
```python
    # project x
    x2 = self.res_to_trans[name](x)

    # cross view attention
    x2 = self.cross_view_attn[name](
        feature_list=[x2],
        xyz_list=[x_xyz[index]],
        shape=shape[:2],
        multiview_data=mv_data,
        voxelize=self.cfg.INPUT.VOXELIZE
    )[0]

    # project back
    x2 = self.trans_to_res[name](x2)

    # skip connection
    x = x + x2
```

**Comment by ayushjain1144** [comment]
Thanks for the question!

You were almost there: `get_multiview_xyz` generates the xyz location for each pixel of the 2D feature maps. "Unprojecting" features is nothing but simply [reshaping](https://github.com/ayushjain1144/odin/blob/main/odin/modeling/meta_arch/cross_view_attention.py#L83) the B, V, H, W, F features to B, N, F features with their corresponding 3D locations coming from `get_multiview_xyz`
