### ISSUE TITLE
'ODIN' object has no attribute 'visualize_pred_on_scannet'

### ISSUE THREAD

**Issue by AaronXenos** [ayushjain1144/odin#14]
"visualize_pred_on_scannet" has no Implementation but be called 
[here](https://github.com/ayushjain1144/odin/blob/main/odin/odin_model.py#L748-L751)

**Comment by ayushjain1144** [comment]
i'll add a fix

**Comment by AaronXenos** [comment]
Is there any update or fix?

**Comment by ayushjain1144** [comment]
Fixed
