### ISSUE TITLE
Demo.py / inference code

### ISSUE THREAD

**Issue by Shuvo001** [ayushjain1144/odin#15]
Thanks for your nice work!
i would like to ask you if you can just add **demo.py** code.
it will be very user friendly and can test the model on our custom .las/bin/ply PC data.
thanks again and looking forward to it.

**Comment by ayushjain1144** [comment]
Hi @Shuvo001 
We have a related request in #10 but I haven't been able to find time to work on this yet. Btw, you would need posed RGB-D as well, and simply ply files won't work. 

I don't anticipate this demo script to be added in very near fututre, but if you do end up working on this and face any issue, please let me know!

**Comment by ayushjain1144** [comment]
Closing this issue, since we have #10 open as a reference.
