### ISSUE TITLE
Code for obtaining the predicted mask on the ScanNet200 dataset

### ISSUE THREAD

**Issue by Yioutpi** [ayushjain1144/odin#18]
Thank you for your excellent work!
 I would like to use ODIN to obtain a 3D mask on the ScanNet200 dataset. I couldn’t find the settings for storing the mask like Maks3D in the README. Could you please provide a method to save the predicted 3D mask? This would be very helpful for me. Thanks again!

**Comment by ayushjain1144** [comment]
Hi, You can look at the following lines: https://github.com/ayushjain1144/odin/blob/main/odin/odin_model.py#L740-L745

You can save the masks/classes/scores from `processed_3d` variable in whatever format you need. Also `export_pred_benchmark` function saves the masks in the format which the benchmark script expects. That might be a good reference too. Let me know if you face any issues 🙂
