### ISSUE TITLE
mask2former

### ISSUE THREAD

**Issue by hfutdzx** [ayushjain1144/odin#23]
thanks for your contribution，i have a question.you trained 2d semantic segmentation.what is 2d semantic segmentation performance(miou) on scannetv2？

**Comment by ayushjain1144** [comment]
Hi, we didn't train for 2d segmentation on scannet. you can do that using our code (with some modifications in data loading), but the 2D scannet labels are not "real" ground truths. More discussion on how to do this and other nuances is in #21. 

(Also, you can take our trained model and just evaluate for per-view 2D semantic segmentation -- either by supplying a single RGB frame as input or by supplying multiple frames and then taking the output produced on each frame as seperate prediction)
