### ISSUE TITLE
Question about scannet point cloud evaluation

### ISSUE THREAD

**Issue by yuqunw** [ayushjain1144/odin#25]
Hi, thanks for introducing and sharing such a great work! I have one question about the ScanNet point cloud evaluation. In the script, if I understand correctly, the maximum input view number is 25. However, in some scenes of ScanNet, the views can be pretty large. How do you predict the point cloud in that case? Is it possible to take all input images as input together? Also, could you describe how the figure 3 in the supplementary material is done, as it seems to take more than 61 images in one single forward loop? Thanks!

**Comment by ayushjain1144** [comment]
Hi, we use 25 images (or lesser) only for training; for evaluation, the model evaluates on all images altogether (https://github.com/ayushjain1144/odin/blob/main/scripts/scannet200/scannet200_resnet.sh#L35 : Here -1 means all images). 

Similarly in figure 3, we evaluate with different number of images at test time.

**Comment by yuqunw** [comment]
I see. Thanks for the quick reply!
