### ISSUE TITLE
CUDA OOM on scannet200 inference 

### ISSUE THREAD

**Issue by miboyu24** [ayushjain1144/odin#27]
Hi. Thanks for the great work.
I run `scripts/scannet200/scannet200_swin.sh` using `scannet200_swin_31.5_76k_5.5k.pth` checkpoint for scannet200 segmentation results on 2 4090GPU.
However I found that it cost large GPU memory. Is this normal? Thanks. 
<img width="865" alt="image" src="https://github.com/user-attachments/assets/b6c4cc00-be9b-445b-88b6-511deef1718a">

**Comment by ayushjain1144** [comment]
I think I was running it on 30G gpus -- but you can perhaps set `MAX_FRAME_NUM -1` to 80 and that should work (with potentially some small drop in performance). 

esentially, this will load at max 80 images per scene during inference -- you can play around with this number.

**Comment by miboyu24** [comment]
It works on A100. Thanks.
