### ISSUE TITLE
environment building issues

### ISSUE THREAD

**Issue by tanmay4269** [ayushjain1144/odin#28]
the wheel for detectron2 and pytorch3d arent building and this is likely due to usage of torch 2.2, could you send me your conda env.yaml?

**Comment by tanmay4269** [comment]
nvm, i was able to install using conda:
conda install -y conda-forge::detectron2
conda install -y pytorch3d::pytorch3d 

but init.sh throws `RuntimeError: Error compiling objects for extension`
full output of running init.sh is [here](https://pastejustit.com/limflxjgnz)

my conda environment: https://pastejustit.com/61bwqgakgk

**Comment by ayushjain1144** [comment]
what's the gcc version you are using? make sure to use a version >=9.2
