### ISSUE TITLE
Segmentation of custom point cloud data

### ISSUE THREAD

**Issue by lemonsstyle** [ayushjain1144/odin#29]
Hello, thank you for your contribution. I would like to ask how to apply it to my own point cloud file for segmentation? Do I need to modify my point cloud file according to the format of a certain test dataset?

**Comment by ayushjain1144** [comment]
Hi @lemonsstyle, I think the easiest would be to modify it in the format of ScanNet or you can write a wrapper that supplies the desired inputs to the model (which are basically camera poses, camera intrinsics, and RGB images)

**Comment by lemonsstyle** [comment]
> Hi @lemonsstyle, I think the easiest would be to modify it in the format of ScanNet or you can write a wrapper that supplies the desired inputs to the model (which are basically camera poses, camera intrinsics, and RGB images)

Hello, thank you for your reply. I am familiar with the second method you mentioned, which is similar to MVS reconstruction datasets such as DTU and TNT (image folder, cams folder, camera parameters. txt)?

**Comment by ayushjain1144** [comment]
Right -- these inputs should work

**Comment by lemonsstyle** [comment]
Okay, I'll give it a try. Thank you very much!
