### ISSUE TITLE
Predictions on ScanNet200 dataset

### ISSUE THREAD

**Issue by aminebdj** [ayushjain1144/odin#3]
Hello,

Thanks a lot for the amazing work,

Could you please share the predicted masks, scores, and classes on the ScanNet200 Dataset?

Many thanks,

**Comment by ayushjain1144** [comment]
Hi @aminebdj, I don't have them saved somewhere -- the eval is pretty quick (I believe ~10 mins on the full val set), so it might not take you a long time to generate them (besides the time to setup the repository -- hopefully that's not too painful). 


If you encounter issues or like me to generate those, let me know -- I will try to get it sometime in the next week.
