### ISSUE TITLE
ai2thor : may be incorrect file? confused name?

### ISSUE THREAD

**Issue by eronez** [ayushjain1144/odin#5]
1. Why use scanenet split files for ai2thor? Maybe it's a mistake.
[https://github.com/ayushjain1144/odin/blob/main/data_preparation/ai2thor/globals_dirs.py](https://github.com/ayushjain1144/odin/blob/main/data_preparation/ai2thor/globals_dirs.py)

2. Difference between splits/**ai2thor_splits** and splits/**ai2thor_splits_repr**? Which should we use?
3. There is no **two_scene.txt** in splits/**ai2thor_splits_repr**. Is there any special meaning?

**Comment by ayushjain1144** [comment]
Thanks for pointing this out!

1. Yes, its a mistake. Pushed a fix.
2. ai2thor_splits. I deleted ai2thor_splits_repr
3. two_scene helps run training and evaluation on same two scenes -- this is useful for running overfitting exps for debugging. 

Please let me know if you face any additional issues or something in README is confusing :)
